const data = [
  {
    id: 1,
    title: 'Car Toys',
    position: 'Front end Developer',
    img: '1.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 2,
    title: 'Carols Daughter',
    position: 'Front end Developer',
    img: '2.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 3,
    title: 'Amazon',
    position: 'Front end Developer',
    img: '3.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 4,
    title: 'Baseball Savings',
    position: 'Front end Developer',
    img: '4.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 5,
    title: 'Ashford',
    position: 'Front end Developer',
    img: '5.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 6,
    title: 'Callaway Golf',
    position: 'Front end Developer',
    img: '6.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 7,
    title: 'Car Toys',
    position: 'Front end Developer',
    position: 'Front end Developer',
    img: '1.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 8,
    title: 'Carols Daughter',
    position: 'Front end Developer',
    img: '2.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 9,
    title: 'Amazon',
    position: 'Front end Developer',
    img: '3.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 10,
    title: 'Baseball Savings',
    position: 'Front end Developer',
    img: '4.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 11,
    title: 'Ashford',
    position: 'Front end Developer',
    img: '5.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: 12,
    title: 'Callaway Golf',
    position: 'Front end Developer',
    img: '6.png',
    location: 'gulshan, dhaka',
    phone: '+123-456789',
    skills: ['html', 'css', 'js', 'scss'],
    email: 'example@email.com',
    url: 'apple.com',
    company: 'apple',
    hourlyRate: '15',
    year: '2014',
    experience: '8',
    applied: '18',
    salary: '$45 - $55k',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
];

export default data;
